const functions = require('firebase-functions');
const express = require('express');
const cors = require('cors');
const { response, request } = require('express');
require('dotenv').config();
// this is a test secret key, normally you would have to hide this
// hidden in dot env file as did not want to push to github

const stripe = require('stripe')(process.env.STRIPE_TEST_KEY);

// To set up an API

// - App config
const app = express();

// - Middleware
app.use(cors({ origin: true }));
app.use(express.json());

// - API routes
app.get('/', (request, response) => response.status(200).send('hello world'));

app.post('/payments/create', async (request, response) => {
  const total = request.query.total;

  console.log('Payment request received >> ', total);

  const paymentIntent = await stripe.paymentIntents.create({
    amount: total,
    currency: 'gbp',
  });
  // status 200 mean good, 201 means good and something is created (created a payment intent)
  response.status(201).send({
    clientSecret: paymentIntent.client_secret,
  });
});

// - Listen command
exports.api = functions.https.onRequest(app);

// API end point generated by cloud functions
// functions[api]: http function initialized (http://localhost:5001/clone-6385b/us-central1/api).
